preferencePageName = V8 Storage Sync

pullCommandName = Pull
pullCommandLabel = Pull
pullCommandTooltip = Get from storage

pushCommandName = Push
pushCommandLabel = Push
pushCommandTooltip = Send to storage